### ISSUE TITLE
[BUG] tox failing to find PYTHONPATH

### ISSUE THREAD

**Issue by jn2clark** [marqo-ai/marqo#110]
**Describe the bug**
Trying to run tox from marqo results in a key error, cannot find PYTHONPATH

```
py38 create: /home/jesse/code/s2search/marqo/.tox/py38
___________________________________________________________________________ summary ____________________________________________________________________________
  py38: commands succeeded
  congratulations :)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 354, in get
    return self.resolved[name]
KeyError: 'PYTHONPATH'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tox", line 11, in <module>
    load_entry_point('tox==3.13.2', 'console_scripts', 'tox')()
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 192, in runcommand
    return self.subcommand_test()
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 220, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/usr/lib/python3/dist-packages/tox/session/commands/run/sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "/usr/lib/python3/dist-packages/tox/venv.py", line 594, in setupenv
    status = self.update(action=action)
  File "/usr/lib/python3/dist-packages/tox/venv.py", line 252, in update
    self.hook.tox_testenv_create(action=action, venv=self)
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3/dist-packages/tox/venv.py", line 682, in tox_testenv_create
    venv._pcall(
  File "/usr/lib/python3/dist-packages/tox/venv.py", line 553, in _pcall
    env = self._get_os_environ(is_test_command=is_test_command)
  File "/usr/lib/python3/dist-packages/tox/venv.py", line 472, in _get_os_environ
    env.update(self.envconfig.setenv)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 370, in __getitem__
    x = self.get(name, self._DUMMY)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 364, in get
    self.resolved[name] = res = self.reader._replace(val)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1516, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1552, in do_replace
    expanded = substitute_once(value)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1550, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1597, in _replace_match
    return self._replace_substitution(match)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1632, in _replace_substitution
    val = self._substitute_from_other_section(sub_key)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1626, in _substitute_from_other_section
    raise tox.exception.ConfigError("substitution key {!r} not found".format(key))
tox.exception.ConfigError: ConfigError: substitution key '/' not found
```

**To Reproduce**
1. cd into marqo
2. run tox

**Expected behavior**
tox runs

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by jn2clark** [comment]
I upgraded tox (`$pip install tox`) and it worked! I cannot recall the original version but the one that worked is 
```
In [1]: import tox

In [2]: tox.__version__
Out[2]: '3.26.0'

```
