### ISSUE TITLE
[BUG] Improve error messaging on image download fail

### ISSUE THREAD

**Issue by Jeadie** [marqo-ai/marqo#189]
**Describe the bug**
With an image url that has non-standard issues, marqo fails because the content is not an image. This leads to an exception message in Marqo that is not informative for users. 

**To Reproduce**
1. Create image index and use image URL as defined below.
```python
mq.index("my-multimodal-index").add_documents([{
    "My Image": "https://upload.wikimedia.org/wikipedia/commons/9/92/2016-11-13_01_Kjeungskj%C3%A6r_Lighthouse%2C_S%C3%B8r-Tr%C3%B8ndelag%2C_Norway.jpg",
    "Description": "The hippopotamus, also called the common hippopotamus or river hippopotamus, is a large semiaquatic mammal native to sub-Saharan Africa",
    "_id": "hippo-facts"
}])
```
2. Observe error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jeadie/Github/marqo/src/marqo/s2_inference/s2_inference.py", line 37, in vectorise
    vectorised = available_models[model_cache_key].encode(content, normalize=normalize_embeddings, **kwargs)
  File "/Users/jeadie/Github/marqo/src/marqo/s2_inference/clip_utils.py", line 231, in encode
    return self.encode_image(inputs, normalize=normalize)
  File "/Users/jeadie/Github/marqo/src/marqo/s2_inference/clip_utils.py", line 200, in encode_image
    image_input = [format_and_load_CLIP_image(images)]
  File "/Users/jeadie/Github/marqo/src/marqo/s2_inference/clip_utils.py", line 81, in format_and_load_CLIP_image
    img = _load_image_from_path(image)
  File "/Users/jeadie/Github/marqo/src/marqo/s2_inference/clip_utils.py", line 60, in _load_image_from_path
    img = Image.open(requests.get(image, stream=True).raw)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x2ad868270>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/jeadie/Github/marqo/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/jeadie/Github/marqo/src/marqo/tensor_search/./api.py", line 113, in search
    return tensor_search.search(
  File "/Users/jeadie/Github/marqo/src/marqo/tensor_search/tensor_search.py", line 751, in search
    search_result = _vector_text_search(
  File "/Users/jeadie/Github/marqo/src/marqo/tensor_search/tensor_search.py", line 910, in _vector_text_search
    vectorised_text = s2_inference.vectorise(
  File "/Users/jeadie/Github/marqo/src/marqo/s2_inference/s2_inference.py", line 39, in vectorise
    raise VectoriseError from e
marqo.s2_inference.errors.VectoriseError: None
```

**Expected behavior**
The problem with this image is that it requires customer user-agent headers that aren't out of the box with marqo. A more clear error message could help diagnose this problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser 0.0.6

**Additional context**
- Need to check response.ok on `requests.get(...` call

**Comment by pandu-k** [comment]
resolved by https://github.com/marqo-ai/marqo/pull/198
