### ISSUE TITLE
[BUG] Attempting to create index by specifying number_of_shards without index_defaults leads to a 500

### ISSUE THREAD

**Issue by tomhamer** [marqo-ai/marqo#254]
**Describe the bug**
I attempted to create an index on Marqo cloud (running 0.0.10) and I received an undescriptive 500. When calling create index without specifying index_defaults. This issue needs to be triaged and sent to cloud or opensource (I havent verified if it also impacts marqo running open source) but adding it here in case any cloud users run into it. 

mq.create_index("tesst",{"number_of_shards": 10}) -> 500 error (as below)

mq.create_index("tesst",{"index_defaults": {}, "number_of_shards": 10}) -> worked!

We should make this error more descriptive.

>>> mq.create_index("tesst",{"number_of_shards": 10})
Traceback (most recent call last):
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 128, in __validate
    request.raise_for_status()
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://zio3sslj5c.execute-api.us-east-1.amazonaws.com/prod/indexes/tesst

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/client.py", line 63, in create_index
    return Index.create(
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/index.py", line 78, in create
    return req.post(f"indexes/{index_name}", body={
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 96, in post
    return self.send_request(s.post, path, body, content_type)
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 74, in send_request
    return self.__validate(response)
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 131, in __validate
    convert_to_marqo_error_and_raise(response=request, err=err)
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 145, in convert_to_marqo_error_and_raise
    raise MarqoWebError(message=response_msg, code=code, error_type=error_type,
marqo.errors.MarqoWebError: MarqoWebError: MarqoWebError Error message: Internal Server Error
status_code: 500, type: unhandled_error_type, code: unhandled_error, link: 
>>> mq.create_index("tesst",{"number_of_shards": 1})
Traceback (most recent call last):
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 128, in __validate
    request.raise_for_status()
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://zio3sslj5c.execute-api.us-east-1.amazonaws.com/prod/indexes/tesst

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/client.py", line 63, in create_index
    return Index.create(
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/index.py", line 78, in create
    return req.post(f"indexes/{index_name}", body={
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 96, in post
    return self.send_request(s.post, path, body, content_type)
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 74, in send_request
    return self.__validate(response)
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 131, in __validate
    convert_to_marqo_error_and_raise(response=request, err=err)
  File "/Users/thomashamer/opt/miniconda3/lib/python3.9/site-packages/marqo/_httprequests.py", line 145, in convert_to_marqo_error_and_raise
    raise MarqoWebError(message=response_msg, code=code, error_type=error_type,
marqo.errors.MarqoWebError: MarqoWebError: MarqoWebError Error message: Internal Server Error
status_code: 500, type: unhandled_error_type, code: unhandled_error, link: 

**To Reproduce**
1. Configure client on marqo cloud version 0.0.10
2. call create index leaving out index_defaults field in index settings as above. 
3. See error

**Expected behavior**

We should get a proper response like "you need to specify index_defaults" and a 400

**Screenshots**

**Desktop (please complete the following information):**
 - Marqo cloud version 0.0.10
 

**Additional context**

**Comment by pandu-k** [comment]
This call to `_autofill_index_settings`: https://github.com/marqo-ai/marqo/blob/mainline/src/marqo/tensor_search/tensor_search.py#L84

It should autofill the default `index_defaults`.

Similar index-settings parsing errors should return a helpful 4xx error, with a link to our create index documentation: https://docs.marqo.ai/0.0.11/API-Reference/indexes/#create-index, https://docs.marqo.ai/0.0.11/API-Reference/settings/

**Comment by pandu-k** [comment]
Default index settings are defined here: https://github.com/marqo-ai/marqo/blob/mainline/src/marqo/tensor_search/configs.py#L6

**Comment by pandu-k** [comment]
The problem is that model check is called before autofill index settings. See here: https://github.com/marqo-ai/marqo/blob/mainline/src/marqo/tensor_search/tensor_search.py#L83
