### ISSUE TITLE
[BUG] Handle Marqo-OS errors better

### ISSUE THREAD

**Issue by pandu-k** [marqo-ai/marqo#316]
**Describe the bug**
In the process of translating a Marqo-OS error into a more understandable one for users,  a parsing error can occur which is given to users as a 500

**To Reproduce**

We can probably reproduce via mocking
1. Mock a request to Marqo-os
2. Make it return an unusually formatted JSON error message

**Expected behavior**
Even if there is an error parsing the Marqo-OS error, it should handle this and return users an appropriate error message (perhaps forwarding the message/status from Marqo-OS

**Comment by pandu-k** [comment]
This is the associated Marqo error logs:

```
2023-02-13T03:18:05.950542854Z INFO:     172.17.0.1:49072 - "POST /indexes/marqo-simplewiki-demo-all/search?&device=cpu HTTP/1.1" 500 Internal Server Error
2023-02-13T03:18:05.960026414Z   warnings.warn(
2023-02-13T03:18:05.960030637Z ERROR:    Exception in ASGI application
2023-02-13T03:18:05.960035082Z Traceback (most recent call last):
2023-02-13T03:18:05.960039483Z   File "/app/src/marqo/_httprequests.py", line 134, in __validate
2023-02-13T03:18:05.960044481Z     request.raise_for_status()
2023-02-13T03:18:05.960048853Z   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1021, in raise_for_status
2023-02-13T03:18:05.960062108Z     raise HTTPError(http_error_msg, response=self)
2023-02-13T03:18:05.960066412Z requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://.../_msearch
2023-02-13T03:18:05.960075767Z During handling of the above exception, another exception occurred:
2023-02-13T03:18:05.960084137Z Traceback (most recent call last):
2023-02-13T03:18:05.960088264Z   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-02-13T03:18:05.960092712Z     result = await app(  # type: ignore[func-returns-value]
2023-02-13T03:18:05.960097493Z   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-02-13T03:18:05.960102355Z     return await self.app(scope, receive, send)
2023-02-13T03:18:05.960115464Z   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 
---- Starlette and FastAPI error handling stuff...
2023-02-13T03:18:05.960240557Z   File "/app/src/marqo/tensor_search/./api.py", line 114, in search
2023-02-13T03:18:05.960244530Z     return tensor_search.search(
2023-02-13T03:18:05.960249268Z   File "/app/src/marqo/tensor_search/tensor_search.py", line 836, in search
2023-02-13T03:18:05.960253688Z     search_result = _vector_text_search(
2023-02-13T03:18:05.960258145Z   File "/app/src/marqo/tensor_search/tensor_search.py", line 1164, in _vector_text_search
2023-02-13T03:18:05.960262589Z     response = HttpRequests(config).get(path=F"{index_name}/_msearch", body=utils.dicts_to_jsonl(body))
2023-02-13T03:18:05.960267393Z   File "/app/src/marqo/_httprequests.py", line 93, in get
2023-02-13T03:18:05.960272166Z     res = self.send_request(requests.get, path=path, body=body, content_type=content_type)
2023-02-13T03:18:05.960276852Z   File "/app/src/marqo/_httprequests.py", line 80, in send_request
2023-02-13T03:18:05.960281211Z     return self.__validate(response)
2023-02-13T03:18:05.960285638Z   File "/app/src/marqo/_httprequests.py", line 137, in __validate
2023-02-13T03:18:05.960290584Z     convert_to_marqo_web_error_and_raise(response=request, err=err)
2023-02-13T03:18:05.960295220Z   File "/app/src/marqo/_httprequests.py", line 159, in convert_to_marqo_web_error_and_raise
2023-02-13T03:18:05.960300381Z     open_search_error_type = response_dict["error"]["type"]
2023-02-13T03:18:05.960305358Z TypeError: string indices must be integers


```

**Comment by pandu-k** [comment]
Probably as simple as catching Type errors, along with key errors
