### ISSUE TITLE
[BUG] Add / Update document using REST API failing with internal server error

### ISSUE THREAD

**Issue by codebrain** [marqo-ai/marqo#320]
**Describe the bug**

POSTing to the `/indexes/<indexname>/documents...` API returns a `500` internal server error.

**To Reproduce**

1. Create the index:

`POST indexes/a746a449-8450-4272-94bb-4ba5b5a5ea5a`

Body:
`{"index_defaults":{"treat_urls_and_pointers_as_images":false,"model":"hf/all_datasets_v4_MiniLM-L6","normalize_embeddings":true,"text_preprocessing":{"split_length":"2","split_overlap":"0","split_method":"sentence"},"image_preprocessing":{}}}`

2. Add the documents:

`POST /indexes/a746a449-8450-4272-94bb-4ba5b5a5ea5a/documents?refresh=true&batch_size=0&processes=1&device=cpu`

Body:
`[{"Title":"The Travels of Marco Polo","Description":"A 13th-century travelogue describing Polos travels"},{"Title":"Extravehicular Mobility Unit (EMU)","Description":"The EMU is a spacesuit that provides environmental protection","_id":"article_591"}]`

**Expected behavior**

Documents to be added.

**Additional context**

Server returns a 500 internal server error, attached is the docker image log:

```
marqo_1  | ERROR:    Exception in ASGI application
marqo_1  | Traceback (most recent call last):
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marqo_1  |     result = await app(  # type: ignore[func-returns-value]
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marqo_1  |     return await self.app(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 270, in __call__
marqo_1  |     await super().__call__(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 124, in __call__
marqo_1  |     await self.middleware_stack(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
marqo_1  |     raise exc
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
marqo_1  |     await self.app(scope, receive, _send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 75, in __call__
marqo_1  |     raise exc
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 64, in __call__
marqo_1  |     await self.app(scope, receive, sender)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marqo_1  |     raise e
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marqo_1  |     await self.app(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 680, in __call__
marqo_1  |     await route.handle(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 275, in handle
marqo_1  |     await self.app(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 65, in app
marqo_1  |     response = await func(request)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 235, in app
marqo_1  |     raw_response = await run_endpoint_function(
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
marqo_1  |     return await run_in_threadpool(dependant.call, **values)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
marqo_1  |     return await anyio.to_thread.run_sync(func, *args)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
marqo_1  |     return await get_asynclib().run_sync_in_worker_thread(
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marqo_1  |     return await future
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
marqo_1  |     result = context.run(func, *args)
marqo_1  |   File "/app/src/marqo/tensor_search/./api.py", line 133, in add_or_replace_documents
marqo_1  |     return tensor_search.add_documents_orchestrator(
marqo_1  |   File "/app/src/marqo/tensor_search/tensor_search.py", line 250, in add_documents_orchestrator
marqo_1  |     return add_documents(
marqo_1  |   File "/app/src/marqo/tensor_search/tensor_search.py", line 462, in add_documents
marqo_1  |     content_chunks = text_processor.split_text(field_content, split_by=split_by, split_length=split_length, split_overlap=split_overlap)
marqo_1  |   File "/app/src/marqo/s2_inference/processing/text.py", line 147, in split_text
marqo_1  |     segments = list(windowed(split_text, n=split_length, step=split_length - split_overlap))
marqo_1  | TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

**Comment by jn2clark** [comment]
hi @codebrain ! thanks for reporting this. it looks like it might be a type error on the settings for the text processing. could you try the following?
`{"index_defaults":{"treat_urls_and_pointers_as_images":false,"model":"hf/all_datasets_v4_MiniLM-L6","normalize_embeddings":true,"text_preprocessing":{"split_length":2,"split_overlap":0,"split_method":"sentence"},"image_preprocessing":{}}}`
[API reference](https://marqo.pages.dev/0.0.12/API-Reference/indexes/)
we can add a better error here and possibly type checking to prevent this from happening.

**Comment by tomhamer** [comment]
@codebrain any chance this can be due to batch_size=0? In any case we should definitely look into validation here

**Comment by codebrain** [comment]
> @jn2clark , trying `{"index_defaults":{"treat_urls_and_pointers_as_images":false,"model":"hf/all_datasets_v4_MiniLM-L6","normalize_embeddings":true,"text_preprocessing":{"split_length":2,"split_overlap":0,"split_method":"sentence"},"image_preprocessing":{}}}`

(these are the defaults I set in the C# client anyway)

Results in an error:

```
marqo_1  | INFO:     172.18.0.1:44962 - "POST /indexes/ccec8d93-b664-417f-b4ec-8380365761b0 HTTP/1.1" 200 OK
marqo_1  | INFO:marqo.tensor_search.tensor_search:batch_size=0 and processes=1 - not doing any marqo side batching
marqo_1  | INFO:     172.18.0.1:44962 - "POST /indexes/ccec8d93-b664-417f-b4ec-8380365761b0/documents?refresh=true&batch_size=0&processes=1&device=cpu HTTP/1.1" 500 Internal Server Error
marqo_1  | ERROR:    Exception in ASGI application
marqo_1  | Traceback (most recent call last):
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marqo_1  |     result = await app(  # type: ignore[func-returns-value]
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marqo_1  |     return await self.app(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 270, in __call__
marqo_1  |     await super().__call__(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 124, in __call__
marqo_1  |     await self.middleware_stack(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
marqo_1  |     raise exc
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
marqo_1  |     await self.app(scope, receive, _send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 75, in __call__
marqo_1  |     raise exc
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 64, in __call__
marqo_1  |     await self.app(scope, receive, sender)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marqo_1  |     raise e
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marqo_1  |     await self.app(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 680, in __call__
marqo_1  |     await route.handle(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 275, in handle
marqo_1  |     await self.app(scope, receive, send)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 65, in app
marqo_1  |     response = await func(request)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 235, in app
marqo_1  |     raw_response = await run_endpoint_function(
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
marqo_1  |     return await run_in_threadpool(dependant.call, **values)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
marqo_1  |     return await anyio.to_thread.run_sync(func, *args)
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
marqo_1  |     return await get_asynclib().run_sync_in_worker_thread(
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marqo_1  |     return await future
marqo_1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
marqo_1  |     result = context.run(func, *args)
marqo_1  |   File "/app/src/marqo/tensor_search/./api.py", line 133, in add_or_replace_documents
marqo_1  |     return tensor_search.add_documents_orchestrator(
marqo_1  |   File "/app/src/marqo/tensor_search/tensor_search.py", line 250, in add_documents_orchestrator
marqo_1  |     return add_documents(
marqo_1  |   File "/app/src/marqo/tensor_search/tensor_search.py", line 462, in add_documents
marqo_1  |     content_chunks = text_processor.split_text(field_content, split_by=split_by, split_length=split_length, split_overlap=split_overlap)
marqo_1  |   File "/app/src/marqo/s2_inference/processing/text.py", line 147, in split_text
marqo_1  |     segments = list(windowed(split_text, n=split_length, step=split_length - split_overlap))
marqo_1  | TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

**Comment by codebrain** [comment]
> @tomhamer - any chance this can be due to batch_size=0? In any case we should definitely look into validation here

I tried `batch_size=1` and still the same error.

**Comment by pandu-k** [comment]
@codebrain index settings text_preprocessing parameter "split_length" and "split_overlap" need to be ints, not strings. This body should work for your create index call:
```
{
	"index_defaults": {
		"treat_urls_and_pointers_as_images": false,
		"model": "hf/all_datasets_v4_MiniLM-L6",
		"normalize_embeddings": true,
		"text_preprocessing": {
			"split_length": 2,
			"split_overlap": 0,
			"split_method": "sentence"
		},
		"image_preprocessing": {}
	}
}
```

**Comment by pandu-k** [comment]
Created a PR to fix this: https://github.com/marqo-ai/marqo/compare/validate_settings.py?expand=1

**Comment by codebrain** [comment]
> @codebrain index settings text_preprocessing parameter "split_length" and "split_overlap" need to be ints, not strings. This body should work for your create index call:

Thank you! I found the problem on my end, the C# model was defined correctly, but I had a serialiser that was overriding the type to a be a json string.
