### ISSUE TITLE
[BUG] Error ingesting simple wiki using simple_wiki_demo script

### ISSUE THREAD

**Issue by supertramp01** [marqo-ai/marqo#828]
**Describe the bug**

Indexing/ingesting docs from simple wiki fails

**To Reproduce**
Follow steps outlined in this page: https://github.com/marqo-ai/marqo/tree/mainline/examples/SimpleWiki

**Expected behavior**

**Screenshots**

2024-05-04 01:38:12,396 logger:'marqo' INFO     add_documents batch 2875: took 1.505s for Marqo to process & index 50 docs. Roundtrip time: 1.515s.
2024-05-04 01:38:14,077 logger:'marqo' INFO     add_documents batch 2876: took 1.673s for Marqo to process & index 50 docs. Roundtrip time: 1.681s.
2024-05-04 01:38:15,881 logger:'marqo' INFO     add_documents batch 2877: took 1.789s for Marqo to process & index 50 docs. Roundtrip time: 1.804s.
Traceback (most recent call last):
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/_httprequests.py", line 141, in _validate
    request.raise_for_status()
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8882/indexes/marqo-simplewiki-demo-all/documents?refresh=false

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/supertramp/repos/marqo/examples/SimpleWiki/simple_wiki_demo.py", line 95, in <module>
    responses = client.index(index_name).add_documents(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/index.py", line 503, in add_documents
    return self._add_docs_organiser(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/index.py", line 553, in _add_docs_organiser
    res = self._batch_request(
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/index.py", line 807, in _batch_request
    results = [verbosely_add_docs(i, docs) for i, docs in enumerate(batched)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/index.py", line 807, in <listcomp>
    results = [verbosely_add_docs(i, docs) for i, docs in enumerate(batched)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/index.py", line 762, in verbosely_add_docs
    res = self.http.post(path=path_with_query_str, body=body, index_name=self.index_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/_httprequests.py", line 101, in post
    return self.send_request('post', path, body, content_type, index_name=index_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/_httprequests.py", line 75, in send_request
    return self._validate(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/_httprequests.py", line 144, in _validate
    convert_to_marqo_error_and_raise(response=request, err=err)
  File "/Users/supertramp/repos/marqo/venv/lib/python3.11/site-packages/marqo/_httprequests.py", line 158, in convert_to_marqo_error_and_raise
    raise MarqoWebError(message=response_msg, code=code, error_type=error_type,
marqo.errors.MarqoWebError: MarqoWebError: MarqoWebError Error message: {'message': "Marqo encountered an unexpected internal error.\nPlease create an issue on Marqo's GitHub repo (https://github.com/marqo-ai/marqo/issues) if this problem persists.", 'code': None, 'type': None, 'link': ''}
status_code: 500, type: None, code: None, link: 

 - OS: MacOS 14.4.1 Sonoma

**Comment by farshidz** [comment]
Hi @supertramp01 . These are your client logs. Could you please post your Marqo logs (printed out  by the Marqo container) so we can investigate this better?
